### PR TITLE
ReaderT version

### PR DESCRIPTION
**Pull request by jeffreyrosenbluth**
## Ready to be considered for meging.
As @byorgey  has pointed out we do some things in `State` that
could be in `Reader`. @cchalmers has a pr open for rasterific. The difference
here is that we still need state to keep track of gradient ids, etc in addition to Reader.

### CODE REVIEW

**Comment by byorgey** [comment]
hehe

**Comment by jeffreyrosenbluth** [comment]
Any objections to merging this?

**Comment by cchalmers** [comment]
LGTM

**Comment by byorgey** [comment]
LGTM as well.

**Pull request merged**
